### ISSUE TITLE
Hockeyplex

### ISSUE THREAD

**Issue by AgomezGZ** [kevcenteno/BallPlex.bundle#10]
It is possible for you to continue the project "hockeyplex" started by FredenFromSweden
http://www6.hockeystreams.com/assist/categories/13/api+discussion/4814/APP+HockeyPlex

**Comment by kevcenteno** [comment]
I could, but I don't have a HockeyStreams account :(

**Comment by AgomezGZ** [comment]
If you need an API Key, I can provide you the one that is linked to my account ;-)

**Comment by kevcenteno** [comment]
Ha!  Thanks, but that's against their TOS, and wouldn't want to risk you losing your account.
