### ISSUE TITLE
Can't Login

### ISSUE THREAD

**Issue by ahaghgoo** [kevcenteno/BallPlex.bundle#11]
For some reason I can't login anymore.  It was working last week, but just tried to login and I've been unsuccessful.  Triple checked my id and password and even changed my password to make sure I got it right.  I can login on the website but not via the Plex app.  Any thoughts as to why? 

Thanks, 
Afshin

**Comment by kevcenteno** [comment]
That's weird... What platform are you on?

**Comment by ahaghgoo** [comment]
Hi Kevin, 

It’s all good now.  The login is saved.  Sorry for the trouble!  -A
