### ISSUE TITLE
Not able to play live games on Apple TV 4

### ISSUE THREAD

**Issue by ahaghgoo** [kevcenteno/BallPlex.bundle#12]
I just got the Apple TV 4 and am trying to play live games via the Plex plugin on my Apple TV, but it doesn't load live games.  I can load games on demand, and can load live games via the Plex plugin from my computer, but not from the Plex app on Apple TV.

**Comment by kevcenteno** [comment]
It's a problem with Plex + Apple TV, not this plugin
