### ISSUE TITLE
"This app isn't supported"

### ISSUE THREAD

**Issue by ee-yun** [kevcenteno/BallPlex.bundle#7]
Hello,

I recently set up BallPlex for my Samsung TV and I'm really excited to use it but when I went into Plex video channel and selected BallPlex, I get the following error:

This app isn't supported
BallPlex .
08-patch requires features that aren't available in the app you're using.

I made sure to enter my log in details in the Media manager on my computer.

Any suggestion on how to fix this?

Thank you

**Comment by kevcenteno** [comment]
@ee-yun Please use this version: https://github.com/kevcenteno/BallPlex.bundle/tree/noRTMP

**Comment by ee-yun** [comment]
this worked like a charm.  you are a god
